#!/usr/bin/env bash
# Download bench data into tests/benches/.data (gitignored). Idempotent; no
# absolute machine paths and no secrets. Optional L3 requires `curl` only and
# leaves a .parquet plus a manifest for the evaluator.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA="$HERE/.data"
mkdir -p "$DATA"

L1_URL="${HUMANEVAL_URL:-https://raw.githubusercontent.com/openai/human-eval/master/data/HumanEval.jsonl.gz}"
L2_URL="${MBPP_URL:-https://raw.githubusercontent.com/google-research/google-research/master/mbpp/mbpp.jsonl}"
L3_URL="${SWE_MINI_URL:-https://modelscope.cn/datasets/evalscope/swe-bench-verified-mini/resolve/master/data/test-00000-of-00001.parquet}"

fetch() {
  local name="$1" url="$2"
  if [[ -f "$DATA/$name" ]]; then
    echo "exists: $DATA/$name"
  else
    echo "fetch: $url"
    curl -fL --retry 3 --max-time 120 "$url" -o "$DATA/$name"
  fi
}

fetch "HumanEval.jsonl.gz" "$L1_URL"
fetch "mbpp.jsonl" "$L2_URL"

if [[ "${SKIP_SWE:-0}" != "1" ]]; then
  fetch "swe-bench-verified-mini.parquet" "$L3_URL" || echo "L3 fetch failed (network/modelscope); L1/L2 remain usable" >&2
fi

cat > "$DATA/MANIFEST.md" <<EOF
# Bench data manifest (generated by fetch-benches.sh)

- HumanEval.jsonl.gz: ${L1_URL}
- mbpp.jsonl: ${L2_URL}
- swe-bench-verified-mini.parquet (optional): ${L3_URL}
EOF

ls -lh "$DATA"
